// Generated by gencpp from file rasbot_msgs/DriveMsg.msg
// DO NOT EDIT!


#ifndef RASBOT_MSGS_MESSAGE_DRIVEMSG_H
#define RASBOT_MSGS_MESSAGE_DRIVEMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rasbot_msgs
{
template <class ContainerAllocator>
struct DriveMsg_
{
  typedef DriveMsg_<ContainerAllocator> Type;

  DriveMsg_()
    : left(0)
    , right(0)  {
    }
  DriveMsg_(const ContainerAllocator& _alloc)
    : left(0)
    , right(0)  {
  (void)_alloc;
    }



   typedef int32_t _left_type;
  _left_type left;

   typedef int32_t _right_type;
  _right_type right;





  typedef boost::shared_ptr< ::rasbot_msgs::DriveMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rasbot_msgs::DriveMsg_<ContainerAllocator> const> ConstPtr;

}; // struct DriveMsg_

typedef ::rasbot_msgs::DriveMsg_<std::allocator<void> > DriveMsg;

typedef boost::shared_ptr< ::rasbot_msgs::DriveMsg > DriveMsgPtr;
typedef boost::shared_ptr< ::rasbot_msgs::DriveMsg const> DriveMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rasbot_msgs::DriveMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rasbot_msgs::DriveMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rasbot_msgs::DriveMsg_<ContainerAllocator1> & lhs, const ::rasbot_msgs::DriveMsg_<ContainerAllocator2> & rhs)
{
  return lhs.left == rhs.left &&
    lhs.right == rhs.right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rasbot_msgs::DriveMsg_<ContainerAllocator1> & lhs, const ::rasbot_msgs::DriveMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rasbot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rasbot_msgs::DriveMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rasbot_msgs::DriveMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rasbot_msgs::DriveMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rasbot_msgs::DriveMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rasbot_msgs::DriveMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rasbot_msgs::DriveMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rasbot_msgs::DriveMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "febc810ab9cc360ca3f47fcee4f2ba71";
  }

  static const char* value(const ::rasbot_msgs::DriveMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfebc810ab9cc360cULL;
  static const uint64_t static_value2 = 0xa3f47fcee4f2ba71ULL;
};

template<class ContainerAllocator>
struct DataType< ::rasbot_msgs::DriveMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rasbot_msgs/DriveMsg";
  }

  static const char* value(const ::rasbot_msgs::DriveMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rasbot_msgs::DriveMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 left\n"
"int32 right\n"
;
  }

  static const char* value(const ::rasbot_msgs::DriveMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rasbot_msgs::DriveMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DriveMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rasbot_msgs::DriveMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rasbot_msgs::DriveMsg_<ContainerAllocator>& v)
  {
    s << indent << "left: ";
    Printer<int32_t>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<int32_t>::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RASBOT_MSGS_MESSAGE_DRIVEMSG_H
